#!/usr/bin/env python3
"""Thai (th) translations for the 226 flat keys missing from translations.ts."""
import json
import re
from pathlib import Path

REPO = Path(r"C:/Users/pc/AppData/Local/hermes/cache/scratch/gh-compare")
TR = REPO / "lib/i18n/translations.ts"
BSLASH = chr(92)

FILLS = {
    "about.badge": "เกี่ยวกับเรา",
    "about.cta.description": "เข้าร่วมกับผู้ใช้หลายพันคนที่หาเงินบิตคอยน์ฟรีทุกวัน สมัครเลยและรับสะโตชิแรกของคุณภายในไม่กี่นาที",
    "about.cta.getStarted": "เริ่มต้น",
    "about.cta.learnMore": "เรียนรู้เพิ่มเติม",
    "about.cta.title": "พร้อมเริ่มหาเงินหรือยัง?",
    "about.description": "พันธกิจของเราคือทำให้คริปโตเคอเรนซีเข้าถึงได้ทุกคนผ่านแพลตฟอร์ม faucet ที่เป็นนวัตกรรมของเรา",
    "about.milestones.claims": "การเคลม",
    "about.milestones.distributed": "สะโตชิที่แจกจ่าย",
    "about.milestones.launch": "การเปิดตัวแพลตฟอร์ม",
    "about.milestones.users": "ผู้ใช้",
    "about.stats.subtitle": "ตัวเลขที่พูดแทนตัวเอง",
    "about.stats.title": "ความสำเร็จของเรา",
    "about.story.description": "ก่อตั้งขึ้นด้วยวิสัยทัศน์เพื่อขจัดข้อจำกัดในการเข้าถึงคริปโต เราเติบโตจากไอเดียง่าย ๆ สู่แพลตฟอร์มที่น่าเชื่อถือซึ่งให้บริการผู้ใช้ทั่วโลก",
    "about.story.mission.description": "มอบวิธีหาคริปโตที่ง่าย ปลอดภัย และมีรางวัลให้ทุกคน ไม่ว่าจะมีความรู้ด้านเทคนิคหรือพื้นฐานทางการเงินอย่างไร",
    "about.story.mission.title": "พันธกิจของเรา",
    "about.story.title": "เรื่องราว",
    "about.story.titleHighlight": "ของเรา",
    "about.story.vision.description": "โลกที่คริปโตเข้าถึงได้ทุกคน และเปิดโอกาสให้ทุกคนมีส่วนร่วมในเศรษฐกิจดิจิทัล",
    "about.story.vision.title": "วิสัยทัศน์ของเรา",
    "about.title": "สร้างอนาคตของ",
    "about.titleEnd": "- ประตูสู่บิตคอยน์ฟรีของคุณ",
    "about.titleHighlight": "การหาเงินจากคริปโต",
    "about.values.community.description": "สร้างโดยชุมชน เพื่อชุมชน ความคิดเห็นของคุณกำหนดรูปแบบแพลตฟอร์มของเรา",
    "about.values.community.title": "ขับเคลื่อนโดยชุมชน",
    "about.values.global.description": "ใช้งานได้ทั่วโลก รองรับหลายภาษาและหลายสกุลเงิน",
    "about.values.global.title": "เข้าถึงทั่วโลก",
    "about.values.instant.description": "ไม่ต้องรอ – ถอนรายได้ของคุณได้ทันทีเมื่อคุณต้องการ",
    "about.values.instant.title": "จ่ายเงินทันที",
    "about.values.security.description": "เราให้ความสำคัญกับความปลอดภัยของเงินและข้อมูลของคุณด้วยมาตรการระดับองค์กร",
    "about.values.security.title": "ความปลอดภัยมาก่อน",
    "about.values.subtitle": "หลักการที่นำทางทุกสิ่งที่เราทำ",
    "about.values.title": "ค่านิยมหลัก",
    "about.values.titleHighlight": "ของเรา",
    "about.why.instant.description": "การถอนถูกดำเนินการทันทีไปยัง FaucetPay",
    "about.why.instant.title": "ดำเนินการทันที",
    "about.why.noFees.description": "ไม่มีค่าใช้จ่ายแอบแฝง หาเท่าไรได้เท่านั้น",
    "about.why.noFees.title": "ศูนย์ค่าธรรมเนียม",
    "about.why.reliable.description": "หลายปีแห่งบริการที่เชื่อถือได้ พร้อมการจ่ายเงินหลายล้าน",
    "about.why.reliable.title": "ความน่าเชื่อถือที่พิสูจน์แล้ว",
    "about.why.secure.description": "บัญชีของคุณได้รับการปกป้องด้วยมาตรการความปลอดภัยขั้นสูง",
    "about.why.secure.title": "ความปลอดภัยระดับธนาคาร",
    "about.why.subtitle": "นี่คือสิ่งที่ทำให้เราแตกต่างจากแพลตฟอร์มอื่น",
    "about.why.support.description": "ทีมสนับสนุนของเราพร้อมช่วยเหลือคุณเสมอ",
    "about.why.support.title": "สนับสนุน 24/7",
    "about.why.title": "ทำไม",
    "about.why.titleHighlight": "ต้องเลือกเรา",
    "about.why.transparent.description": "เงื่อนไขชัดเจน ไม่มีเซอร์ไพรส์ ติดตามทุกอย่างแบบเรียลไทม์",
    "about.why.transparent.title": "โปร่งใสเต็มรูปแบบ",
    "admin.action.approve": "อนุมัติ",
    "admin.action.ban": "แบนผู้ใช้",
    "admin.action.cancel": "ยกเลิก",
    "admin.action.confirm": "ยืนยัน",
    "admin.action.delete": "ลบ",
    "admin.action.edit": "แก้ไข",
    "admin.action.error": "การดำเนินการล้มเหลว",
    "admin.action.flag": "ทำเครื่องหมายผู้ใช้",
    "admin.action.processing": "กำลังดำเนินการ...",
    "admin.action.reject": "ปฏิเสธ",
    "admin.action.review": "ตรวจสอบ",
    "admin.action.save": "บันทึก",
    "admin.action.success": "ดำเนินการสำเร็จ",
    "admin.action.unban": "ปลดแบน",
    "admin.action.unflag": "ยกเลิกเครื่องหมาย",
    "admin.dashboard.activeUsers": "ผู้ใช้ที่ใช้งานอยู่",
    "admin.dashboard.fraudAlerts": "การแจ้งเตือนการฉ้อโกง",
    "admin.dashboard.pendingWithdrawals": "การถอนที่รอดำเนินการ",
    "admin.dashboard.title": "แดชบอร์ดผู้ดูแล",
    "admin.dashboard.totalClaims": "การเคลมทั้งหมด",
    "admin.dashboard.totalPaidOut": "จ่ายออกทั้งหมด",
    "admin.dashboard.totalUsers": "ผู้ใช้ทั้งหมด",
    "admin.header.noPending": "ไม่มีการแจ้งเตือนที่รอดำเนินการ",
    "admin.header.notifications": "การแจ้งเตือนผู้ดูแล",
    "admin.header.search": "ค้นหาผู้ใช้ ธุรกรรม...",
    "admin.header.viewAllAlerts": "ดูการแจ้งเตือนทั้งหมด",
    "admin.nav.adManagement": "การจัดการโฆษณา",
    "admin.nav.analytics": "การวิเคราะห์",
    "admin.nav.auditLogs": "บันทึกการตรวจสอบ",
    "admin.nav.backToUserView": "กลับสู่มุมมองผู้ใช้",
    "admin.nav.boosters": "บูสเตอร์",
    "admin.nav.coupons": "คูปอง",
    "admin.nav.dashboard": "ภาพรวม",
    "admin.nav.envVars": "ตัวแปรสภาพแวดล้อม",
    "admin.nav.fraudReview": "ตรวจสอบการฉ้อโกง",
    "admin.nav.funds": "การจัดการเงินทุน",
    "admin.nav.notifications": "การแจ้งเตือน",
    "admin.nav.permissions": "สิทธิ์",
    "admin.nav.settings": "การตั้งค่า",
    "admin.nav.shortlinks": "ลิงก์สั้น",
    "admin.nav.systemSettings": "การตั้งค่าระบบ",
    "admin.nav.tournaments": "ทัวร์นาเมนต์",
    "admin.nav.transactions": "ธุรกรรม",
    "admin.nav.users": "ผู้ใช้",
    "admin.nav.withdrawals": "การถอน",
    "admin.status.active": "ใช้งาน",
    "admin.status.approved": "อนุมัติแล้ว",
    "admin.status.banned": "ถูกแบน",
    "admin.status.flagged": "ถูกทำเครื่องหมาย",
    "admin.status.pending": "รอดำเนินการ",
    "admin.status.rejected": "ถูกปฏิเสธ",
    "admin.status.unverified": "ยังไม่ยืนยัน",
    "admin.status.verified": "ยืนยันแล้ว",
    "badge.admin": "ผู้ดูแล",
    "badge.beta": "เบต้า",
    "badge.hot": "ฮิต",
    "badge.new": "ใหม่",
    "badge.verified": "ยืนยันแล้ว",
    "blog.articles": "บทความ",
    "blog.badge": "อัปเดตล่าสุด",
    "blog.clearFilters": "ล้างตัวกรอง",
    "blog.description": "ติดตามข่าวสาร เคล็ดลับ และข้อมูลเชิงลึกล่าสุดจากโลกคริปโต",
    "blog.emailPlaceholder": "กรอกอีเมลของคุณ",
    "blog.loadMore": "โหลดบทความเพิ่มเติม",
    "blog.loading": "กำลังโหลด...",
    "blog.newsletter": "จดหมายข่าว",
    "blog.newsletterDesc": "รับข่าวคริปโตล่าสุด คู่มือ และเคล็ดลับพิเศษส่งตรงถึงกล่องจดหมายของคุณ",
    "blog.noResults": "ไม่พบบทความที่ตรงกับเกณฑ์ของคุณ",
    "blog.noSpam": "ไม่มีสแปม ยกเลิกการติดตามได้ตลอดเวลา",
    "blog.of": "จาก",
    "blog.published": "เผยแพร่",
    "blog.search": "ค้นหา",
    "blog.searchPlaceholder": "ค้นหาบทความ...",
    "blog.showing": "กำลังแสดง",
    "blog.stayUpdated": "ติดตามข่าวสาร",
    "blog.subscribe": "สมัครรับข่าว",
    "blog.titleHighlight": "บล็อก",
    "common.noData": "ไม่มีข้อมูล",
    "common.noResults": "ไม่พบผลลัพธ์",
    "common.seeAll": "ดูทั้งหมด",
    "common.showLess": "แสดงน้อยลง",
    "common.showMore": "แสดงเพิ่มเติม",
    "common.tryAgain": "ลองอีกครั้ง",
    "common.view": "ดู",
    "contact.badge": "ติดต่อเรา",
    "contact.chat.link": "เข้าร่วม Discord",
    "contact.chat.title": "แชทสด",
    "contact.description": "มีคำถามหรือต้องการความช่วยเหลือ? เราพร้อมช่วยเสมอ",
    "contact.email.title": "สนับสนุนทางอีเมล",
    "contact.form.description": "กรอกแบบฟอร์มด้านล่าง แล้วเราจะติดต่อกลับโดยเร็วที่สุด",
    "contact.form.email": "อีเมล",
    "contact.form.emailPlaceholder": "ofyou@email.com",
    "contact.form.error": "ส่งข้อความไม่สำเร็จ โปรดลองอีกครั้ง",
    "contact.form.message": "ข้อความ",
    "contact.form.messagePlaceholder": "บอกเราว่าเราช่วยอะไรคุณได้บ้าง...",
    "contact.form.name": "ชื่อ",
    "contact.form.namePlaceholder": "ชื่อของคุณ",
    "contact.form.other": "อื่น ๆ",
    "contact.form.sending": "กำลังส่ง...",
    "contact.form.subject": "หัวข้อ",
    "contact.form.subject.account": "ปัญหาบัญชี",
    "contact.form.subject.feedback": "ข้อเสนอแนะ",
    "contact.form.subject.general": "สอบถามทั่วไป",
    "contact.form.subject.other": "อื่น ๆ",
    "contact.form.subject.partnership": "ความร่วมมือ",
    "contact.form.subject.support": "สนับสนุนด้านเทคนิค",
    "contact.form.subject.withdrawal": "ปัญหาการถอน",
    "contact.form.subjectPlaceholder": "เลือกหัวข้อ",
    "contact.form.submit": "ส่งข้อความ",
    "contact.form.success": "ส่งข้อความสำเร็จ!",
    "contact.form.title": "ส่งข้อความถึงเรา",
    "contact.response.description": "โดยปกติเราจะตอบกลับภายใน 24 ชั่วโมงในวันทำการ",
    "contact.response.title": "เวลาตอบกลับ",
    "contact.success.another": "ส่งข้อความอื่น",
    "contact.success.description": "ขอบคุณที่ติดต่อเรา เราจะตอบกลับภายใน 24 ชั่วโมง",
    "contact.success.title": "ส่งข้อความแล้ว!",
    "contact.title": "ติดต่อ",
    "contact.titleHighlight": "ทีมงานของเรา",
    "cta.badge": "เริ่มหาเงินวันนี้",
    "cta.button": "เริ่มฟรี",
    "cta.description": "เข้าร่วมกับผู้ใช้หลายพันคนที่กำลังหาบิตคอยน์ฟรี สมัครภายในไม่กี่นาทีและเริ่มเก็บสะโตชิได้เลย",
    "cta.noCard": "ไม่ต้องใช้บัตรเครดิต",
    "cta.signIn": "เข้าสู่ระบบ",
    "cta.title": "พร้อมเริ่มต้น",
    "cta.titleHighlight": "หาเงินจากคริปโต",
    "dashboard.availableBalance": "ยอดคงเหลือที่ใช้ได้",
    "dashboard.balance": "ยอดคงเหลือ",
    "dashboard.claimNow": "เคลมเลย",
    "dashboard.claimReady": "พร้อมเคลม!",
    "dashboard.copyLink": "คัดลอกลิงก์แนะนำ",
    "dashboard.header.allCaughtUp": "คุณอ่านครบแล้ว!",
    "dashboard.header.dayStreak": "วันต่อเนื่อง",
    "dashboard.header.loading": "กำลังโหลด...",
    "dashboard.header.markAllRead": "ทำเครื่องหมายว่าอ่านแล้วทั้งหมด",
    "dashboard.header.noNotifications": "ไม่มีการแจ้งเตือน",
    "dashboard.header.notifications": "การแจ้งเตือน",
    "dashboard.header.suspended": "ถูกระงับ",
    "dashboard.header.underReview": "อยู่ระหว่างตรวจสอบ",
    "dashboard.header.viewAll": "ดูการแจ้งเตือนทั้งหมด",
    "dashboard.linkCopied": "คัดลอกลิงก์แล้ว!",
    "dashboard.nav.adminPanel": "แผงผู้ดูแล",
    "dashboard.nav.administration": "การจัดการระบบ",
    "dashboard.nav.days": "วัน",
    "dashboard.nav.earnMore": "หาเงินเพิ่ม",
    "dashboard.nav.manualFaucet": "ฟอสเอตแบบเลือกเอง",
    "dashboard.nav.navigation": "การนำทาง",
    "dashboard.nav.refs": "ผู้แนะนำ",
    "dashboard.nav.support": "สนับสนุน",
    "dashboard.nav.yourBalance": "ยอดคงเหลือของคุณ",
    "dashboard.nextClaim": "การเคลมถัดไป",
    "dashboard.pendingWithdrawals": "การถอนที่รอดำเนินการ",
    "dashboard.streak": "สตรีค",
    "dashboard.streakBonus": "โบนัสสตรีค",
    "dashboard.totalEarned": "รายได้รวม",
    "dashboard.viewHistory": "ดูประวัติ",
    "dashboard.waitTime": "เวลารอ",
    "dashboard.withdraw": "ถอน",
    "faq.badge": "คำถามที่พบบ่อย",
    "faq.contact": "ยังมีคำถามอยู่ไหม?",
    "faq.contactButton": "ติดต่อฝ่ายสนับสนุน",
    "faq.subtitle": "ทุกสิ่งที่คุณต้องรู้เกี่ยวกับแพลตฟอร์มของเรา",
    "faq.title": "คำถาม",
    "faq.titleHighlight": "ที่พบบ่อย",
    "features.claim.description": "ไม่ต้องรอนาน หาสะโตชิฟรีทุก 5 นาที",
    "features.claim.title": "เคลมทุก 5 นาที",
    "features.dashboard.description": "ติดตามรายได้และเฝ้าดูความคืบหน้าแบบเรียลไทม์",
    "features.dashboard.title": "แดชบอร์ดเรียลไทม์",
    "features.referral.description": "รับ 10% จากการแนะนำโดยตรง, 5% จากระดับ 2 และ 2% จากระดับ 3",
    "features.referral.title": "ระบบแนะนำ 3 ระดับ",
    "features.security.description": "การตรวจจับการฉ้อโกงขั้นสูง รองรับ 2FA และข้อมูลเข้ารหัส",
    "features.security.title": "ความปลอดภัยระดับองค์กร",
    "features.streak.description": "สร้างสตรีคของคุณและรับสูงสุด 100% เพิ่มในทุกการเคลม",
    "features.streak.title": "โบนัสสตรีครายวัน",
    "features.subtitle": "แพลตฟอร์มของเราออกแบบมาเพื่อช่วยคุณหาเงินมากขึ้นโดยใช้แรงน้อยลง",
    "features.title": "ทุกสิ่งที่คุณต้องมีเพื่อ",
    "features.titleHighlight": "เพิ่มรายได้สูงสุด",
    "features.withdraw.description": "ถอนรายได้ของคุณทันทีไปยัง FaucetPay",
    "features.withdraw.title": "ถอนไปยัง FaucetPay ทันที",
    "footer.aml": "นโยบาย AML",
    "footer.about": "เกี่ยวกับเรา",
    "footer.api": "API",
    "footer.blog": "บล็อก",
    "footer.community": "ชุมชน",
    "footer.company": "บริษัท",
    "footer.contact": "ติดต่อ",
    "footer.cookies": "นโยบายคุกกี้",
    "footer.description": "แพลตฟอร์มฟอสเอตคริปโตที่น่าเชื่อถือที่สุด หาบิตคอยน์ฟรีทุก 5 นาทีพร้อมถอนเข้า FaucetPay ทันที",
    "footer.help": "ศูนย์ช่วยเหลือ",
    "footer.legal": "ข้อกฎหมาย",
    "footer.privacy": "นโยบายความเป็นส่วนตัว",
    "footer.product": "ผลิตภัณฑ์",
    "footer.status": "สถานะระบบ",
    "footer.support": "สนับสนุน",
    "footer.terms": "ข้อกำหนดการใช้บริการ",
    "hero.trust.trustedGeneric": "แพลตฟอร์มที่น่าเชื่อถือ",
    "hero.trust.trustedWithCount": "{count} ผู้ใช้เชื่อถือเรา",
    "hero.badge": "หาบิตคอยน์ทุก 5 นาที",
    "hero.title": "แพลตฟอร์ม",
    "hero.titleHighlight": "ฟอสเอตคริปโต",
    "hero.titleEnd": "ที่น่าเชื่อถือที่สุด",
    "hero.description": "เคลมสะโตชิฟรีทุก 5 นาที สร้างโบนัสสตรีครายวัน เชิญเพื่อน และถอนเข้า FaucetPay ได้ทันที",
    "hero.cta.start": "เริ่มหาเงินเดี๋ยวนี้",
    "hero.cta.learn": "เรียนรู้เพิ่มเติม",
    "hero.trust.secure": "ปลอดภัยและเข้ารหัส",
    "hero.trust.instant": "ถอนทันที",
    "hero.trust.trusted": "ผู้ใช้กว่า 10,000 คนเชื่อถือเรา",
    "howItWorks.step": "ขั้นตอน",
    "howItWorks.subtitle": "การเริ่มต้นง่ายมาก ทำตามขั้นตอนเหล่านี้แล้วเริ่มหาเงินวันนี้",
    "howItWorks.title": "เริ่มหาเงินใน",
    "howItWorks.titleHighlight": "4 ขั้นตอนง่าย ๆ",
    "language.title": "ภาษา",
    "stats.claimsToday": "เคลมวันนี้",
    "stats.paidOut": "จ่ายออกทั้งหมด",
    "stats.users": "ผู้ใช้ที่ใช้งานอยู่",
    "stats.totalClaims": "การเคลมทั้งหมด",
    "testimonials.badge": "ความเห็นจากผู้ใช้",
    "testimonials.subtitle": "ดูว่าชุมชนของเราพูดถึงการหาเงินกับเราอย่างไร",
    "testimonials.title": "เชื่อถือโดย",
    "testimonials.titleHighlight": "ผู้หาเงินหลายพันคน",
    "theme.dark": "โหมดมืด",
    "theme.light": "โหมดสว่าง",
    "theme.system": "ตามระบบ",
    "theme.title": "ธีม",
    "time.daysAgo": "วันที่แล้ว",
    "time.hoursAgo": "ชั่วโมงที่แล้ว",
    "time.justNow": "เมื่อสักครู่",
    "time.minutesAgo": "นาทีที่แล้ว",
    "time.monthsAgo": "เดือนที่แล้ว",
    "time.weeksAgo": "สัปดาห์ที่แล้ว",
    "userMenu.adminPanel": "แผงผู้ดูแล",
    "userMenu.dashboard": "แดชบอร์ด",
    "userMenu.getStarted": "เริ่มต้น",
    "userMenu.helpCenter": "ศูนย์ช่วยเหลือ",
    "userMenu.history": "ประวัติ",
    "userMenu.profile": "โปรไฟล์",
    "userMenu.referrals": "ผู้แนะนำ",
    "userMenu.settings": "การตั้งค่า",
    "userMenu.signIn": "เข้าสู่ระบบ",
    "userMenu.signOut": "ออกจากระบบ",
    "userMenu.signingOut": "กำลังออกจากระบบ...",
    "userMenu.withdrawals": "การถอน",
}


def find_block_end(src: str, entry_start: int) -> int:
    i = src.index("{", entry_start)
    depth = 0
    in_str = False
    while i < len(src):
        c = src[i]
        if in_str:
            if c == BSLASH:
                i += 2
                continue
            if c == '"':
                in_str = False
        else:
            if c == '"':
                in_str = True
            elif c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return i
        i += 1
    raise ValueError("unbalanced braces")


src = TR.read_text(encoding="utf-8")
m = re.search(r"\nconst th: Record<TranslationKey, string> = \{", src)
if not m:
    raise SystemExit("th block not found")
close_brace = find_block_end(src, m.start())
interior = src[src.index("{", m.start()) + 1:close_brace]
already = set(re.findall(r'\n\s+"([a-zA-Z.]+)":', interior))
additions = []
for k, v in FILLS.items():
    if k in already:
        continue
    safe_v = v.replace(BSLASH, BSLASH + BSLASH).replace('"', BSLASH + '"')
    additions.append(f'  "{k}": "{safe_v}",')
insert = "\n" + "\n".join(additions)
src = src[:close_brace] + insert + src[close_brace:]
TR.write_text(src, encoding="utf-8")
print(f"th: +{len(additions)} keys")
