#!/usr/bin/env python3
"""Arabic (ar) translations for the 236 flat keys missing from translations.ts."""
import json
import re
from pathlib import Path

REPO = Path(r"C:/Users/pc/AppData/Local/hermes/cache/scratch/gh-compare")
TR = REPO / "lib/i18n/translations.ts"
BSLASH = chr(92)

FILLS = {
    "about.badge": "من نحن",
    "about.cta.description": "انضم إلى آلاف المستخدمين الذين يكسبون بيتكوين مجانًا كل يوم. سجّل الآن واحصل على أولى الساتوشي خلال دقائق.",
    "about.cta.getStarted": "ابدأ",
    "about.cta.learnMore": "اعرف المزيد",
    "about.cta.title": "جاهز لبدء الكسب؟",
    "about.description": "مهمتنا هي جعل العملات الرقمية في متناول الجميع من خلال منصة الحنفية المبتكرة لدينا.",
    "about.milestones.claims": "المطالبات",
    "about.milestones.distributed": "ساتوشي موزعة",
    "about.milestones.launch": "إطلاق المنصة",
    "about.milestones.users": "المستخدمون",
    "about.stats.subtitle": "أرقام تتحدث عن نفسها",
    "about.stats.title": "معالمنا",
    "about.story.description": "تأسسنا برؤية دمقرطة الوصول إلى العملات الرقمية، ونما فكرتنا من فكرة بسيطة إلى منصة موثوقة تخدم المستخدمين في جميع أنحاء العالم.",
    "about.story.mission.description": "تزويد الجميع بطريقة بسيطة وآمنة ومجزئة لكسب العملات الرقمية، بغض النظر عن خبرتهم التقنية أو خلفيتهم المالية.",
    "about.story.mission.title": "مهمتنا",
    "about.story.title": "قصتنا",
    "about.story.titleHighlight": "",
    "about.story.vision.description": "عالمٌ تكون فيه العملات الرقمية في متناول الجميع، وتمكّن الأفراد من المشاركة في الاقتصاد الرقمي.",
    "about.story.vision.title": "رؤيتنا",
    "about.title": "نبني مستقبل",
    "about.titleEnd": "- بوابتك إلى البيتكوين المجاني",
    "about.titleHighlight": "أرباح العملات الرقمية",
    "about.values.community.description": "بُنيت من قبل المجتمع، لأجل المجتمع. ملاحظاتك تشكّل منصتنا.",
    "about.values.community.title": "يقوده المجتمع",
    "about.values.global.description": "متاح في جميع أنحاء العالم مع دعم لغات وعملات متعددة.",
    "about.values.global.title": "وصول عالمي",
    "about.values.instant.description": "بدون انتظار – اسحب أرباحك فورًا متى شئت.",
    "about.values.instant.title": "مدفوعات فورية",
    "about.values.security.description": "نُعطي الأولوية لأمان أموالك وبياناتك بإجراءات أمنية بمستوى المؤسسات.",
    "about.values.security.title": "الأمان أولاً",
    "about.values.subtitle": "المبادئ التي توجّه كل ما نقوم به",
    "about.values.title": "قيمنا",
    "about.values.titleHighlight": "الأساسية",
    "about.why.instant.description": "تُعالج عمليات السحب فورًا إلى FaucetPay.",
    "about.why.instant.title": "معالجة فورية",
    "about.why.noFees.description": "لا تكاليف خفية. ما تكسبه هو ما تحصل عليه.",
    "about.why.noFees.title": "بدون رسوم",
    "about.why.reliable.description": "سنوات من الخدمة الموثوقة مع ملايين المدفوعات.",
    "about.why.reliable.title": "سجل موثوق مثبت",
    "about.why.secure.description": "حسابك محمي بإجراءات أمنية متقدمة.",
    "about.why.secure.title": "أمان بمستوى البنوك",
    "about.why.subtitle": "هذا ما يميزنا عن المنصات الأخرى",
    "about.why.support.description": "فريق الدعم لدينا جاهز دائمًا لمساعدتك.",
    "about.why.support.title": "دعم على مدار الساعة",
    "about.why.title": "لماذا",
    "about.why.titleHighlight": "تختارنا",
    "about.why.transparent.description": "شروط واضحة، دون مفاجآت. تابع كل شيء في الوقت الفعلي.",
    "about.why.transparent.title": "شفافية كاملة",
    "admin.action.approve": "موافقة",
    "admin.action.ban": "حظر المستخدم",
    "admin.action.cancel": "إلغاء",
    "admin.action.confirm": "تأكيد",
    "admin.action.delete": "حذف",
    "admin.action.edit": "تعديل",
    "admin.action.error": "فشلت الإجراء",
    "admin.action.flag": "وضع علامة على المستخدم",
    "admin.action.processing": "جارٍ المعالجة...",
    "admin.action.reject": "رفض",
    "admin.action.review": "مراجعة",
    "admin.action.save": "حفظ",
    "admin.action.success": "تمت الإجراء بنجاح",
    "admin.action.unban": "رفع الحظر",
    "admin.action.unflag": "إزالة العلامة",
    "admin.dashboard.activeUsers": "المستخدمون النشطون",
    "admin.dashboard.fraudAlerts": "تنبيهات الاحتيال",
    "admin.dashboard.pendingWithdrawals": "عمليات السحب المعلقة",
    "admin.dashboard.title": "لوحة تحكم المسؤول",
    "admin.dashboard.totalClaims": "إجمالي المطالبات",
    "admin.dashboard.totalPaidOut": "إجمالي المدفوعات",
    "admin.dashboard.totalUsers": "إجمالي المستخدمين",
    "admin.header.noPending": "لا إشعارات معلقة",
    "admin.header.notifications": "إشعارات المسؤول",
    "admin.header.search": "ابحث عن مستخدم، معاملة...",
    "admin.header.viewAllAlerts": "عرض كل التنبيهات",
    "admin.nav.adManagement": "إدارة الإعلانات",
    "admin.nav.analytics": "التحليلات",
    "admin.nav.auditLogs": "سجلات التدقيق",
    "admin.nav.backToUserView": "العودة إلى واجهة المستخدم",
    "admin.nav.boosters": "المعززات",
    "admin.nav.coupons": "أكواد القسائم",
    "admin.nav.dashboard": "نظرة عامة",
    "admin.nav.envVars": "متغيرات البيئة",
    "admin.nav.fraudReview": "مراجعة الاحتيال",
    "admin.nav.funds": "إدارة الأموال",
    "admin.nav.notifications": "الإشعارات",
    "admin.nav.permissions": "الأذونات",
    "admin.nav.settings": "الإعدادات",
    "admin.nav.shortlinks": "الروابط المختصرة",
    "admin.nav.systemSettings": "إعدادات النظام",
    "admin.nav.tournaments": "البطولات",
    "admin.nav.transactions": "المعاملات",
    "admin.nav.users": "المستخدمون",
    "admin.nav.withdrawals": "عمليات السحب",
    "admin.status.active": "نشط",
    "admin.status.approved": "معتمد",
    "admin.status.banned": "محظور",
    "admin.status.flagged": "مُعلَّم",
    "admin.status.pending": "معلق",
    "admin.status.rejected": "مرفوض",
    "admin.status.unverified": "غير موثق",
    "admin.status.verified": "موثق",
    "badge.admin": "مسؤول",
    "badge.beta": "تجريبي",
    "badge.hot": "رائج",
    "badge.new": "جديد",
    "badge.verified": "موثق",
    "blog.articles": "مقالات",
    "blog.badge": "أحدث التحديثات",
    "blog.clearFilters": "مسح الفلاتر",
    "blog.description": "ابقَ على اطلاع بأحدث أخبار ونصائح ورؤى عالم العملات الرقمية.",
    "blog.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "blog.loadMore": "تحميل المزيد من المقالات",
    "blog.loading": "جارٍ التحميل...",
    "blog.newsletter": "النشرة البريدية",
    "blog.newsletterDesc": "احصل على أحدث أخبار العملات الرقمية والأدلة والنصائح الحصرية مباشرة في بريدك.",
    "blog.noResults": "لا توجد مقالات تطابق معاييرك.",
    "blog.noSpam": "بدون رسائل مزعجة. يمكنك إلغاء الاشتراك في أي وقت.",
    "blog.of": "من",
    "blog.published": "نُشر",
    "blog.search": "بحث",
    "blog.searchPlaceholder": "ابحث في المقالات...",
    "blog.showing": "عرض",
    "blog.stayUpdated": "ابقَ على اطلاع",
    "blog.subscribe": "اشترك",
    "blog.titleHighlight": "المدونة",
    "common.noData": "لا توجد بيانات",
    "common.noResults": "لا توجد نتائج",
    "common.seeAll": "عرض الكل",
    "common.showLess": "عرض أقل",
    "common.showMore": "عرض المزيد",
    "common.tryAgain": "حاول مجددًا",
    "common.view": "عرض",
    "contact.badge": "تواصل معنا",
    "contact.chat.link": "انضم إلى Discord",
    "contact.chat.title": "محادثة مباشرة",
    "contact.description": "لديك أسئلة أو تحتاج مساعدة؟ نحن هنا من أجلك.",
    "contact.email.title": "الدعم عبر البريد الإلكتروني",
    "contact.form.description": "املأ النموذج أدناه وسنعود إليك في أقرب وقت ممكن.",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.emailPlaceholder": "your@email.com",
    "contact.form.error": "فشل إرسال الرسالة. حاول مجددًا.",
    "contact.form.message": "الرسالة",
    "contact.form.messagePlaceholder": "أخبرنا كيف يمكننا المساعدة...",
    "contact.form.name": "الاسم",
    "contact.form.namePlaceholder": "اسمك",
    "contact.form.other": "أخرى",
    "contact.form.sending": "جارٍ الإرسال...",
    "contact.form.subject": "الموضوع",
    "contact.form.subject.account": "مشكلة في الحساب",
    "contact.form.subject.feedback": "ملاحظات",
    "contact.form.subject.general": "استفسار عام",
    "contact.form.subject.other": "أخرى",
    "contact.form.subject.partnership": "شراكة",
    "contact.form.subject.support": "الدعم الفني",
    "contact.form.subject.withdrawal": "مشكلة في السحب",
    "contact.form.subjectPlaceholder": "اختر موضوعًا",
    "contact.form.submit": "إرسال الرسالة",
    "contact.form.success": "تم إرسال الرسالة بنجاح!",
    "contact.form.title": "أرسل لنا رسالة",
    "contact.response.description": "نرد عادةً خلال 24 ساعة في أيام العمل.",
    "contact.response.title": "وقت الاستجابة",
    "contact.success.another": "إرسال رسالة أخرى",
    "contact.success.description": "شكرًا لتواصلك. سنرد خلال 24 ساعة.",
    "contact.success.title": "تم إرسال الرسالة!",
    "contact.title": "اتصل بنا",
    "contact.titleHighlight": "فريقنا",
    "cta.badge": "ابدأ الكسب اليوم",
    "cta.button": "ابدأ مجانًا",
    "cta.description": "انضم إلى آلاف المستخدمين الذين يكسبون بيتكوين مجانًا بالفعل. سجّل خلال دقائق وابدأ جمع الساتوشي الآن.",
    "cta.noCard": "لا حاجة لبطاقة ائتمان",
    "cta.signIn": "تسجيل الدخول",
    "cta.title": "جاهز للبدء",
    "cta.titleHighlight": "اكسب العملات الرقمية",
    "dashboard.availableBalance": "الرصيد المتاح",
    "dashboard.balance": "الرصيد",
    "dashboard.claimNow": "اطلب الآن",
    "dashboard.claimReady": "المطالبة جاهزة!",
    "dashboard.copyLink": "انسخ رابط الإحالة",
    "dashboard.header.allCaughtUp": "لقد اطّلعت على كل شيء!",
    "dashboard.header.dayStreak": "أيام متتالية",
    "dashboard.header.loading": "جارٍ التحميل...",
    "dashboard.header.markAllRead": "وضع علامة مقروء على الكل",
    "dashboard.header.noNotifications": "لا إشعارات",
    "dashboard.header.notifications": "الإشعارات",
    "dashboard.header.suspended": "معلّق",
    "dashboard.header.underReview": "قيد المراجعة",
    "dashboard.header.viewAll": "عرض كل الإشعارات",
    "dashboard.linkCopied": "تم نسخ الرابط!",
    "dashboard.nav.adminPanel": "لوحة المسؤول",
    "dashboard.nav.administration": "الإدارة",
    "dashboard.nav.days": "أيام",
    "dashboard.nav.earnMore": "اكسب المزيد",
    "dashboard.nav.manualFaucet": "الحنفية اليدوية",
    "dashboard.nav.navigation": "التنقل",
    "dashboard.nav.refs": "إحالات",
    "dashboard.nav.support": "الدعم",
    "dashboard.nav.yourBalance": "رصيدك",
    "dashboard.nextClaim": "المطالبة التالية",
    "dashboard.pendingWithdrawals": "عمليات السحب المعلقة",
    "dashboard.streak": "سلسلة",
    "dashboard.streakBonus": "مكافأة السلسلة",
    "dashboard.totalEarned": "إجمالي الأرباح",
    "dashboard.viewHistory": "عرض السجل",
    "dashboard.waitTime": "وقت الانتظار",
    "dashboard.withdraw": "اسحب",
    "faq.badge": "الأسئلة الشائعة",
    "faq.contact": "ما زالت لديك أسئلة؟",
    "faq.contactButton": "تواصل مع الدعم",
    "faq.subtitle": "كل ما تحتاج معرفته عن منصتنا.",
    "faq.title": "الأسئلة",
    "faq.titleHighlight": "الشائعة",
    "features.claim.description": "لا انتظار طويل. اكسب ساتوشي مجانية كل 5 دقائق.",
    "features.claim.title": "اطلب كل 5 دقائق",
    "features.dashboard.description": "تتبع أرباحك وراقب تقدمك في الوقت الفعلي.",
    "features.dashboard.title": "لوحة تحكم في الوقت الفعلي",
    "features.referral.description": "اكسب 10% من الإحالات المباشرة، و5% من المستوى الثاني، و2% من المستوى الثالث.",
    "features.referral.title": "نظام إحالات من 3 مستويات",
    "features.security.description": "كشف احتيال متقدم، ودعم 2FA، وبيانات مشفرة.",
    "features.security.title": "أمان بمستوى المؤسسات",
    "features.streak.description": "ابنِ سلسلتك واكسب حتى 100% إضافية في كل مطالبة.",
    "features.streak.title": "مكافآت السلسلة اليومية",
    "features.subtitle": "منصتنا مصممة لمساعدتك على كسب المزيد بجهد أقل.",
    "features.title": "كل ما تحتاجه لـ",
    "features.titleHighlight": "تعظيم أرباحك",
    "features.withdraw.description": "اسحب أرباحك فورًا إلى FaucetPay.",
    "features.withdraw.title": "سحوبات فورية عبر FaucetPay",
    "footer.aml": "سياسة AML",
    "footer.about": "من نحن",
    "footer.api": "API",
    "footer.blog": "المدونة",
    "footer.community": "المجتمع",
    "footer.company": "الشركة",
    "footer.contact": "اتصل بنا",
    "footer.cookies": "سياسة ملفات الارتباط",
    "footer.description": "منصة الحنفية الأكثر موثوقية للعملات الرقمية. اكسب بيتكوين مجانًا كل 5 دقائق مع سحوبات فورية عبر FaucetPay.",
    "footer.help": "مركز المساعدة",
    "footer.legal": "قانوني",
    "footer.privacy": "سياسة الخصوصية",
    "footer.product": "المنتج",
    "footer.status": "حالة النظام",
    "footer.support": "الدعم",
    "footer.terms": "شروط الخدمة",
    "hero.trust.trustedGeneric": "منصة موثوقة",
    "hero.trust.trustedWithCount": "{count} مستخدم يثقون بنا",
    "hero.badge": "اكسب بيتكوين كل 5 دقائق",
    "hero.title": "منصة",
    "hero.titleHighlight": "الحنفية الرقمية",
    "hero.titleEnd": "الأكثر موثوقية",
    "hero.description": "اطلب ساتوشي مجانية كل 5 دقائق، وابنِ مكافآت السلسلة اليومية، وادعُ أصدقاءك، واسحب فورًا إلى FaucetPay.",
    "hero.cta.start": "ابدأ الكسب الآن",
    "hero.cta.learn": "اعرف المزيد",
    "hero.trust.secure": "آمن ومشفّر",
    "hero.trust.instant": "سحوبات فورية",
    "hero.trust.trusted": "أكثر من 10 آلاف مستخدم يثقون بنا",
    "howItWorks.step": "خطوة",
    "howItWorks.subtitle": "البداية سهلة. اتبع هذه الخطوات وابدأ الكسب اليوم.",
    "howItWorks.title": "ابدأ الكسب في",
    "howItWorks.titleHighlight": "4 خطوات بسيطة",
    "language.title": "اللغة",
    "stats.claimsToday": "مطالبات اليوم",
    "stats.paidOut": "إجمالي المدفوعات",
    "stats.users": "المستخدمون النشطون",
    "stats.totalClaims": "إجمالي المطالبات",
    "testimonials.badge": "آراء المستخدمين",
    "testimonials.subtitle": "اكتشف ما يقوله مجتمعنا عن الكسب معنا.",
    "testimonials.title": "يثق بنا",
    "testimonials.titleHighlight": "آلاف الكاسبين",
    "theme.dark": "داكن",
    "theme.light": "فاتح",
    "theme.system": "النظام",
    "theme.title": "المظهر",
    "userMenu.adminPanel": "لوحة المسؤول",
    "userMenu.dashboard": "لوحة التحكم",
    "userMenu.getStarted": "ابدأ",
    "userMenu.helpCenter": "مركز المساعدة",
    "userMenu.history": "السجل",
    "userMenu.profile": "الملف الشخصي",
    "userMenu.referrals": "الإحالات",
    "userMenu.settings": "الإعدادات",
    "userMenu.signIn": "تسجيل الدخول",
    "userMenu.signOut": "تسجيل الخروج",
    "userMenu.signingOut": "جارٍ تسجيل الخروج...",
    "userMenu.withdrawals": "عمليات السحب",
}


def find_block_end(src: str, entry_start: int) -> int:
    i = src.index("{", entry_start)
    depth = 0
    in_str = False
    while i < len(src):
        c = src[i]
        if in_str:
            if c == BSLASH:
                i += 2
                continue
            if c == '"':
                in_str = False
        else:
            if c == '"':
                in_str = True
            elif c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return i
        i += 1
    raise ValueError("unbalanced braces")


src = TR.read_text(encoding="utf-8")
m = re.search(r"\nconst ar: Record<TranslationKey, string> = \{", src)
if not m:
    raise SystemExit("ar block not found")
close_brace = find_block_end(src, m.start())
interior = src[src.index("{", m.start()) + 1:close_brace]
already = set(re.findall(r'\n\s+"([a-zA-Z.]+)":', interior))
additions = []
for k, v in FILLS.items():
    if k in already:
        continue
    safe_v = v.replace(BSLASH, BSLASH + BSLASH).replace('"', BSLASH + '"')
    additions.append(f'  "{k}": "{safe_v}",')
insert = "\n" + "\n".join(additions)
src = src[:close_brace] + insert + src[close_brace:]
TR.write_text(src, encoding="utf-8")
print(f"ar: +{len(additions)} keys")
