#!/usr/bin/env python3
"""Final gap-fill for hi (139) and it (133) — the remaining keys are mostly
about/contact/features/footer/hero. Translations appended into their blocks."""
import json
import re
from pathlib import Path

REPO = Path(r"C:/Users/pc/AppData/Local/hermes/cache/scratch/gh-compare")
TR = REPO / "lib/i18n/translations.ts"
BSLASH = chr(92)

HI2 = {
    "about.why.instant.description": "निकासी तुरंत FaucetPay में संसाधित होती हैं।",
    "about.why.noFees.description": "कोई छिपी लागत नहीं। आप जो कमाते हैं वही आपको मिलता है।",
    "about.badge": "हमारे बारे में",
    "about.cta.getStarted": "शुरू करें",
    "about.cta.learnMore": "और जानें",
    "about.description": "हमारा मिशन अपने अभिनव फ़ॉसेट प्लेटफ़ॉर्म के माध्यम से क्रिप्टोकरेंसी को सभी के लिए सुलभ बनाना है।",
    "about.milestones.claims": "दावे",
    "about.milestones.distributed": "वितरित सैटोशी",
    "about.milestones.launch": "प्लेटफ़ॉर्म लॉन्च",
    "about.milestones.users": "उपयोगकर्ता",
    "about.stats.subtitle": "आंकड़े जो खुद बोलते हैं",
    "about.stats.title": "हमारे मील के पत्थर",
    "about.story.description": "क्रिप्टोकरेंसी तक पहुंच को लोकतांत्रिक बनाने के दृष्टिकोण के साथ स्थापित, हम एक सरल विचार से दुनिया भर के उपयोगकर्ताओं की सेवा करने वाला एक विश्वसनीय प्लेटफ़ॉर्म बन गए।",
    "about.story.mission.description": "तकनीकी विशेषज्ञता या वित्तीय पृष्ठभूमि की परवाह किए बिना, सभी को क्रिप्टोकरेंसी कमाने का एक सरल, सुरक्षित और पुरस्कृत तरीका प्रदान करना।",
    "about.story.mission.title": "हमारा मिशन",
    "about.story.title": "हमारी",
    "about.story.titleHighlight": "कहानी",
    "about.story.vision.description": "एक ऐसी दुनिया जहां क्रिप्टोकरेंसी सभी के लिए सुलभ हो, जो व्यक्तियों को डिजिटल अर्थव्यवस्था में भाग लेने के लिए सशक्त बनाती है।",
    "about.story.vision.title": "हमारा दृष्टिकोण",
    "about.title": "का भविष्य बना रहे हैं",
    "about.titleEnd": "- मुफ़्त बिटकॉइन का आपका रास्ता",
    "about.titleHighlight": "क्रिप्टो कमाई",
    "about.values.community.description": "समुदाय द्वारा, समुदाय के लिए निर्मित। आपकी प्रतिक्रिया हमारे प्लेटफ़ॉर्म को आकार देती है।",
    "about.values.community.title": "समुदाय-संचालित",
    "about.values.global.description": "कई भाषाओं और मुद्राओं के समर्थन के साथ दुनिया भर में उपलब्ध।",
    "about.values.global.title": "वैश्विक पहुंच",
    "about.values.instant.description": "कोई प्रतीक्षा नहीं – अपनी कमाई जब चाहें तुरंत निकालें।",
    "about.values.instant.title": "तुरंत भुगतान",
    "about.values.security.description": "एंटरप्राइज़-ग्रेड सुरक्षा उपायों के साथ हम आपके फंड और डेटा की सुरक्षा को प्राथमिकता देते हैं।",
    "about.values.security.title": "सुरक्षा सर्वोपरि",
    "about.values.subtitle": "वे सिद्धांत जो हमारे हर काम का मार्गदर्शन करते हैं",
    "about.values.title": "हमारे मूल",
    "about.values.titleHighlight": "मूल्य",
    "about.why.instant.title": "तुरंत प्रसंस्करण",
    "about.why.noFees.title": "शून्य शुल्क",
    "about.why.reliable.description": "लाखों भुगतानों के साथ वर्षों की विश्वसनीय सेवा।",
    "about.why.reliable.title": "प्रमाणित ट्रैक रिकॉर्ड",
    "about.why.secure.description": "आपका खाता उन्नत सुरक्षा उपायों से सुरक्षित है।",
    "about.why.secure.title": "बैंक-स्तरीय सुरक्षा",
    "about.why.subtitle": "यही हमें अन्य प्लेटफ़ॉर्मों से अलग करता है",
    "about.why.support.description": "हमारी सहायता टीम हमेशा आपकी मदद के लिए तैयार है।",
    "about.why.support.title": "24/7 सहायता",
    "about.why.title": "क्यों",
    "about.why.titleHighlight": "हमें चुनें",
    "about.why.transparent.description": "स्पष्ट शर्तें, कोई आश्चर्य नहीं। सब कुछ वास्तविक समय में ट्रैक करें।",
    "about.why.transparent.title": "पूर्ण पारदर्शिता",
    "contact.badge": "संपर्क करें",
    "contact.chat.link": "Discord से जुड़ें",
    "contact.chat.title": "लाइव चैट",
    "contact.description": "प्रश्न हैं या सहायता चाहिए? हम आपके लिए यहाँ हैं।",
    "contact.email.title": "ईमेल सहायता",
    "contact.form.description": "नीचे दिया गया फ़ॉर्म भरें और हम जल्द से जल्द संपर्क करेंगे।",
    "contact.form.email": "ईमेल",
    "contact.form.emailPlaceholder": "aapka@email.com",
    "contact.form.error": "संदेश भेजने में विफल। कृपया पुनः प्रयास करें।",
    "contact.form.message": "संदेश",
    "contact.form.messagePlaceholder": "बताएं हम कैसे मदद कर सकते हैं...",
    "contact.form.name": "नाम",
    "contact.form.namePlaceholder": "आपका नाम",
    "contact.form.other": "अन्य",
    "contact.form.sending": "भेज रहे हैं...",
    "contact.form.subject": "विषय",
    "contact.form.subject.account": "खाता समस्या",
    "contact.form.subject.feedback": "प्रतिक्रिया",
    "contact.form.subject.general": "सामान्य पूछताछ",
    "contact.form.subject.other": "अन्य",
    "contact.form.subject.partnership": "साझेदारी",
    "contact.form.subject.support": "तकनीकी सहायता",
    "contact.form.subject.withdrawal": "निकासी समस्या",
    "contact.form.subjectPlaceholder": "एक विषय चुनें",
    "contact.form.submit": "संदेश भेजें",
    "contact.form.success": "संदेश सफलतापूर्वक भेजा गया!",
    "contact.form.title": "हमें संदेश भेजें",
    "contact.response.description": "कार्य दिवसों पर हम आमतौर पर 24 घंटों के भीतर जवाब देते हैं।",
    "contact.response.title": "प्रतिक्रिया समय",
    "contact.success.another": "एक और संदेश भेजें",
    "contact.success.description": "संपर्क करने के लिए धन्यवाद। हम 24 घंटों के भीतर जवाब देंगे।",
    "contact.success.title": "संदेश भेजा गया!",
    "contact.title": "संपर्क",
    "contact.titleHighlight": "हमारी टीम",
    "cta.badge": "आज कमाई शुरू करें",
    "cta.button": "मुफ़्त में शुरू करें",
    "cta.description": "हज़ारों उपयोगकर्ताओं के साथ जुड़ें जो पहले से मुफ़्त बिटकॉइन कमा रहे हैं। कुछ ही मिनटों में साइन अप करें और अभी सैटोशी कमाना शुरू करें।",
    "cta.noCard": "क्रेडिट कार्ड की आवश्यकता नहीं",
    "cta.signIn": "साइन इन करें",
    "cta.title": "शुरू करने के लिए तैयार",
    "cta.titleHighlight": "क्रिप्टो कमाएं",
    "faq.badge": "अक्सर पूछे जाने वाले प्रश्न",
    "faq.contact": "अभी भी प्रश्न हैं?",
    "faq.contactButton": "सहायता से संपर्क करें",
    "faq.subtitle": "हमारे प्लेटफ़ॉर्म के बारे में वह सब जो आपको जानना चाहिए।",
    "faq.title": "अक्सर",
    "faq.titleHighlight": "पूछे जाने वाले प्रश्न",
    "features.claim.description": "कोई लंबी प्रतीक्षा नहीं। हर 5 मिनट में मुफ़्त सैटोशी कमाएं।",
    "features.claim.title": "हर 5 मिनट में क्लेम",
    "features.dashboard.description": "अपनी कमाई को ट्रैक करें और अपनी प्रगति वास्तविक समय में देखें।",
    "features.dashboard.title": "वास्तविक समय डैशबोर्ड",
    "features.referral.description": "प्रत्यक्ष रेफ़रल से 10%, स्तर 2 से 5% और स्तर 3 से 2% कमाएं।",
    "features.referral.title": "3-स्तरीय रेफ़रल सिस्टम",
    "features.security.description": "उन्नत धोखाधड़ी पहचान, 2FA समर्थन और एन्क्रिप्टेड डेटा।",
    "features.security.title": "एंटरप्राइज़-ग्रेड सुरक्षा",
    "features.streak.description": "अपनी लय बनाएं और हर क्लेम पर 100% तक अतिरिक्त कमाएं।",
    "features.streak.title": "दैनिक लय बोनस",
    "features.subtitle": "हमारा प्लेटफ़ॉर्म आपको कम मेहनत में अधिक कमाने में मदद करने के लिए बनाया गया है।",
    "features.title": "वह सब जो आपको",
    "features.titleHighlight": "अपनी कमाई अधिकतम करने के लिए चाहिए",
    "features.withdraw.description": "अपनी कमाई तुरंत FaucetPay में निकालें।",
    "features.withdraw.title": "FaucetPay पर तुरंत निकासी",
    "footer.aml": "AML नीति",
    "footer.about": "हमारे बारे में",
    "footer.api": "API",
    "footer.blog": "ब्लॉग",
    "footer.community": "समुदाय",
    "footer.company": "कंपनी",
    "footer.contact": "संपर्क",
    "footer.cookies": "कुकी नीति",
    "footer.description": "सबसे विश्वसनीय क्रिप्टो फ़ॉसेट प्लेटफ़ॉर्म। हर 5 मिनट में मुफ़्त बिटकॉइन कमाएं, FaucetPay पर तुरंत निकासी के साथ।",
    "footer.help": "सहायता केंद्र",
    "footer.legal": "कानूनी",
    "footer.privacy": "गोपनीयता नीति",
    "footer.product": "उत्पाद",
    "footer.status": "सिस्टम स्थिति",
    "footer.support": "सहायता",
    "footer.terms": "सेवा की शर्तें",
    "hero.trust.trustedGeneric": "विश्वसनीय प्लेटफ़ॉर्म",
    "hero.trust.trustedWithCount": "{count} उपयोगकर्ताओं का भरोसा",
    "hero.badge": "हर 5 मिनट में बिटकॉइन कमाएं",
    "hero.title": "प्लेटफ़ॉर्म",
    "hero.titleHighlight": "क्रिप्टो फ़ॉसेट",
    "hero.titleEnd": "सबसे विश्वसनीय",
    "hero.description": "हर 5 मिनट में मुफ़्त सैटोशी का दावा करें, दैनिक स्ट्रीक बोनस बनाएं, दोस्तों को आमंत्रित करें और FaucetPay पर तुरंत निकालें।",
    "hero.cta.start": "अभी कमाई शुरू करें",
    "hero.cta.learn": "और जानें",
    "hero.trust.secure": "सुरक्षित और एन्क्रिप्टेड",
    "hero.trust.instant": "तुरंत निकासी",
    "hero.trust.trusted": "10K+ उपयोगकर्ताओं का भरोसा",
    "howItWorks.step": "चरण",
    "howItWorks.subtitle": "शुरुआत करना आसान है। इन चरणों का पालन करें और आज कमाई शुरू करें।",
    "howItWorks.title": "कमाई शुरू करें",
    "howItWorks.titleHighlight": "4 सरल चरणों में",
    "nav.dashboard": "डैशबोर्ड",
    "nav.logout": "लॉग आउट",
    "nav.menu": "मेनू",
    "nav.settings": "सेटिंग्स",
    "language.title": "भाषा",
    "stats.claimsToday": "आज के दावे",
    "stats.paidOut": "कुल भुगतान",
    "stats.users": "सक्रिय उपयोगकर्ता",
    "stats.totalClaims": "कुल दावे",
    "testimonials.badge": "प्रशंसापत्र",
    "testimonials.subtitle": "देखें हमारा समुदाय हमारे साथ कमाई के बारे में क्या कहता है।",
    "testimonials.title": "भरोसा करते हैं",
    "testimonials.titleHighlight": "हज़ारों कमाई करने वाले",
    "theme.dark": "डार्क",
    "theme.light": "लाइट",
    "theme.system": "सिस्टम",
    "theme.title": "थीम",
    "common.back": "वापस",
    "common.cancel": "रद्द करें",
}

IT2 = {
    "about.badge": "Chi siamo",
    "about.cta.getStarted": "Inizia",
    "about.cta.learnMore": "Scopri di più",
    "about.description": "La nostra missione è rendere le criptovalute accessibili a tutti grazie alla nostra piattaforma faucet innovativa.",
    "about.milestones.claims": "Riscatti",
    "about.milestones.distributed": "Satoshi distribuiti",
    "about.milestones.launch": "Lancio della piattaforma",
    "about.milestones.users": "Utenti",
    "about.stats.subtitle": "Numeri che parlano da soli",
    "about.stats.title": "I nostri traguardi",
    "about.story.description": "Fondata con la visione di democratizzare l'accesso alle criptovalute, siamo cresciuti da una semplice idea a una piattaforma affidabile al servizio di utenti in tutto il mondo.",
    "about.story.mission.description": "Offrire a tutti un modo semplice, sicuro e gratificante di guadagnare criptovalute, indipendentemente dalle competenze tecniche o dal background finanziario.",
    "about.story.mission.title": "La nostra missione",
    "about.story.title": "La nostra",
    "about.story.titleHighlight": "storia",
    "about.story.vision.description": "Un mondo in cui le criptovalute sono accessibili a tutti, consentendo agli individui di partecipare all'economia digitale.",
    "about.story.vision.title": "La nostra visione",
    "about.title": "Costruiamo il futuro di",
    "about.titleEnd": "- La tua porta verso i Bitcoin gratis",
    "about.titleHighlight": "guadagni in cripto",
    "about.values.community.description": "Costruita dalla comunità, per la comunità. Il tuo feedback modella la nostra piattaforma.",
    "about.values.community.title": "Guidata dalla comunità",
    "about.values.global.description": "Disponibile in tutto il mondo con supporto per più lingue e valute.",
    "about.values.global.title": "Accesso globale",
    "about.values.instant.description": "Nessuna attesa – preleva i tuoi guadagni istantaneamente, quando vuoi.",
    "about.values.instant.title": "Prelievi istantanei",
    "about.values.security.description": "Diamo priorità alla sicurezza dei tuoi fondi e dati con misure di livello aziendale.",
    "about.values.security.title": "Sicurezza prima di tutto",
    "about.values.subtitle": "I principi che guidano tutto ciò che facciamo",
    "about.values.title": "I nostri valori",
    "about.values.titleHighlight": "fondamentali",
    "about.why.instant.description": "I prelievi vengono elaborati istantaneamente verso FaucetPay.",
    "about.why.instant.title": "Elaborazione istantanea",
    "about.why.noFees.description": "Nessun costo nascosto. Ciò che guadagni è ciò che ottieni.",
    "about.why.noFees.title": "Zero commissioni",
    "about.why.reliable.description": "Anni di servizio affidabile con milioni pagati.",
    "about.why.reliable.title": "Affidabilità comprovata",
    "about.why.secure.description": "Il tuo account è protetto con misure di sicurezza avanzate.",
    "about.why.secure.title": "Sicurezza di livello bancario",
    "about.why.subtitle": "Ecco cosa ci distingue dalle altre piattaforme",
    "about.why.support.description": "Il nostro team di assistenza è sempre pronto ad aiutarti.",
    "about.why.support.title": "Assistenza 24/7",
    "about.why.title": "Perché",
    "about.why.titleHighlight": "scegliere noi",
    "about.why.transparent.description": "Termini chiari, nessuna sorpresa. Segui tutto in tempo reale.",
    "about.why.transparent.title": "Trasparenza totale",
    "contact.badge": "Contattaci",
    "contact.chat.link": "Unisciti a Discord",
    "contact.chat.title": "Chat in diretta",
    "contact.description": "Hai domande o ti serve aiuto? Siamo qui per te.",
    "contact.email.title": "Assistenza email",
    "contact.form.description": "Compila il modulo qui sotto e ti ricontatteremo al più presto.",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "tua@email.com",
    "contact.form.error": "Invio del messaggio non riuscito. Riprova.",
    "contact.form.message": "Messaggio",
    "contact.form.messagePlaceholder": "Dicci come possiamo aiutarti...",
    "contact.form.name": "Nome",
    "contact.form.namePlaceholder": "Il tuo nome",
    "contact.form.other": "Altro",
    "contact.form.sending": "Invio...",
    "contact.form.subject": "Oggetto",
    "contact.form.subject.account": "Problema con l'account",
    "contact.form.subject.feedback": "Feedback",
    "contact.form.subject.general": "Richiesta generale",
    "contact.form.subject.other": "Altro",
    "contact.form.subject.partnership": "Partnership",
    "contact.form.subject.support": "Assistenza tecnica",
    "contact.form.subject.withdrawal": "Problema di prelievo",
    "contact.form.subjectPlaceholder": "Seleziona un oggetto",
    "contact.form.submit": "Invia messaggio",
    "contact.form.success": "Messaggio inviato con successo!",
    "contact.form.title": "Scrivici",
    "contact.response.description": "Di solito rispondiamo entro 24 ore nei giorni lavorativi.",
    "contact.response.title": "Tempo di risposta",
    "contact.success.another": "Invia un altro messaggio",
    "contact.success.description": "Grazie per averci contattato. Risponderemo entro 24 ore.",
    "contact.success.title": "Messaggio inviato!",
    "contact.title": "Contatti",
    "contact.titleHighlight": "il nostro team",
    "cta.badge": "Inizia a guadagnare oggi",
    "cta.button": "Inizia gratis",
    "cta.description": "Unisciti a migliaia di utenti che guadagnano già Bitcoin gratis. Registrati in pochi minuti e inizia a riscattare satoshi adesso.",
    "cta.noCard": "Nessuna carta di credito richiesta",
    "cta.signIn": "Accedi",
    "cta.title": "Pronto a iniziare",
    "cta.titleHighlight": "guadagna cripto",
    "faq.badge": "Domande frequenti",
    "faq.contact": "Hai ancora domande?",
    "faq.contactButton": "Contatta l'assistenza",
    "faq.subtitle": "Tutto quello che c'è da sapere sulla nostra piattaforma.",
    "faq.title": "Domande",
    "faq.titleHighlight": "frequenti",
    "features.claim.description": "Nessuna lunga attesa. Guadagna satoshi gratis ogni 5 minuti.",
    "features.claim.title": "Riscatta ogni 5 minuti",
    "features.dashboard.description": "Traccia i tuoi guadagni e monitora i tuoi progressi in tempo reale.",
    "features.dashboard.title": "Pannello in tempo reale",
    "features.referral.description": "Guadagna il 10% dagli inviti diretti, il 5% dal livello 2 e il 2% dal livello 3.",
    "features.referral.title": "Sistema di inviti a 3 livelli",
    "features.security.description": "Rilevamento frodi avanzato, supporto 2FA e dati crittografati.",
    "features.security.title": "Sicurezza di livello aziendale",
    "features.streak.description": "Costruisci la tua serie e guadagna fino al 100% in più a ogni riscatto.",
    "features.streak.title": "Bonus giornalieri di serie",
    "features.subtitle": "La nostra piattaforma è progettata per aiutarti a guadagnare di più con meno sforzo.",
    "features.title": "Tutto quello che ti serve per",
    "features.titleHighlight": "massimizzare i tuoi guadagni",
    "features.withdraw.description": "Preleva i tuoi guadagni istantaneamente verso FaucetPay.",
    "features.withdraw.title": "Prelievi istantanei su FaucetPay",
    "footer.aml": "Politica AML",
    "footer.about": "Chi siamo",
    "footer.api": "API",
    "footer.blog": "Blog",
    "footer.community": "Comunità",
    "footer.company": "Azienda",
    "footer.contact": "Contatti",
    "footer.cookies": "Policy sui cookie",
    "footer.description": "La piattaforma faucet crypto più affidabile. Guadagna Bitcoin gratis ogni 5 minuti con prelievi istantanei su FaucetPay.",
    "footer.help": "Centro assistenza",
    "footer.legal": "Legale",
    "footer.privacy": "Privacy policy",
    "footer.product": "Prodotto",
    "footer.status": "Stato del sistema",
    "footer.support": "Assistenza",
    "footer.terms": "Termini di servizio",
    "hero.trust.trustedGeneric": "Piattaforma affidabile",
    "hero.trust.trustedWithCount": "{count} utenti si fidano di noi",
    "hero.badge": "Guadagna Bitcoin ogni 5 minuti",
    "hero.title": "La piattaforma",
    "hero.titleHighlight": "Crypto Faucet",
    "hero.titleEnd": "più affidabile",
    "hero.description": "Riscatta satoshi gratis ogni 5 minuti, costruisci bonus di serie giornalieri, invita amici e preleva istantaneamente su FaucetPay.",
    "hero.cta.start": "Inizia a guadagnare ora",
    "hero.cta.learn": "Scopri di più",
    "hero.trust.secure": "Sicuro e crittografato",
    "hero.trust.instant": "Prelievi istantanei",
    "hero.trust.trusted": "Oltre 10K utenti si fidano di noi",
    "howItWorks.step": "Passo",
    "howItWorks.subtitle": "Iniziare è facile. Segui questi passi e inizia a guadagnare oggi.",
    "howItWorks.title": "Inizia a guadagnare in",
    "howItWorks.titleHighlight": "4 semplici passi",
    "nav.dashboard": "Pannello",
    "nav.logout": "Esci",
    "nav.menu": "Menu",
    "nav.settings": "Impostazioni",
    "language.title": "Lingua",
    "stats.claimsToday": "Riscatti di oggi",
    "stats.paidOut": "Totale pagato",
    "stats.users": "Utenti attivi",
    "stats.totalClaims": "Riscatti totali",
    "testimonials.badge": "Recensioni",
    "testimonials.subtitle": "Scopri cosa dice la nostra community sul guadagnare con noi.",
    "testimonials.title": "Apprezzato da",
    "testimonials.titleHighlight": "migliaia di utenti",
    "theme.dark": "Scuro",
    "theme.light": "Chiaro",
    "theme.system": "Sistema",
    "theme.title": "Tema",
    "time.daysAgo": "giorni fa",
    "time.hoursAgo": "ore fa",
    "time.justNow": "Proprio ora",
    "time.minutesAgo": "minuti fa",
    "time.monthsAgo": "mesi fa",
    "time.weeksAgo": "settimane fa",
    "common.back": "Indietro",
    "common.cancel": "Annulla",
    "common.close": "Chiudi",
    "common.error": "Errore",
}

src = TR.read_text(encoding="utf-8")
total = 0
for loc, fills in (("hi", HI2), ("it", IT2)):
    m = re.search(r"\n  %s: \{(.*?\n  \})," % loc, src, re.S)
    if not m:
        print(f"{loc}: BLOCK NOT FOUND")
        continue
    block = m.group(1)
    already = set(re.findall(r'\n\s+"([a-zA-Z.]+)":', block))
    additions = []
    for k, v in fills.items():
        if k in already:
            continue
        safe_v = v.replace(BSLASH, BSLASH + BSLASH).replace('"', BSLASH + '"')
        additions.append(f'  "{k}": "{safe_v}",')
    if not additions:
        print(f"{loc}: nothing to add")
        continue
    close_pos = m.end(1) + len(block)
    src = src[:close_pos] + "\n" + "\n".join(additions) + src[close_pos:]
    total += len(additions)
    print(f"{loc}: +{len(additions)} keys")

TR.write_text(src, encoding="utf-8")
print(f"TOTAL ADDED: {total}")
